import pinkShirttBoy from "../../assets/images/cards/pinkShritboy.png";

export const MsgDummyProfileData = [
  {
    id: 1,
    name: "Eten Hunt",
    role: "Agents",
    message: "Thank you very much. I’m glad ...",
    isMe: false,
    profilePic: pinkShirttBoy,
  },
  {
    id: 2,
    name: "Jakob Saris",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    profilePic: pinkShirttBoy,
  },
  {
    id: 3,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: pinkShirttBoy,
  },
  {
    id: 4,
    name: "Nadia Lauren",
    role: "agents",
    message: "Thank you very much. I’m glad ...",
    isMe: false,
    lastSeen: 5,
    isUnread: true,
    profilePic: pinkShirttBoy,
  },
  {
    id: 5,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: pinkShirttBoy,
  },
  {
    id: 6,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: pinkShirttBoy,
  },
  {
    id: 7,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: pinkShirttBoy,
  },
  {
    id: 8,
    name: "Jakob Saris",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    profilePic: pinkShirttBoy,
  },
  {
    id: 9,
    name: "Eten Hunt",
    role: "agents",
    message: "Thank you very much. I’m glad ...",
    isMe: false,
    profilePic: pinkShirttBoy,
  },
  {
    id: 10,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: pinkShirttBoy,
  },
  {
    id: 11,
    name: "Jakob Saris",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    profilePic: pinkShirttBoy,
  },
  {
    id: 12,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: pinkShirttBoy,
  },
  {
    id: 13,
    name: "Nadia Lauren",
    role: "agents",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    isUnread: true,
    profilePic: pinkShirttBoy,
  },
];
