import { createSlice } from "@reduxjs/toolkit";
import moment from "moment";
import pinkShirttBoy from "../../assets/images/cards/pinkShritboy.png";
import profilePic from "../../assets/images/cards/pinkShritboy.png";
import brokenMan from "../../assets/images/cards/brokenMan.png";
import yellowBoy from "../../assets/images/cards/yellowBoy.png";

// Dummy Users List
const users = [
  {
    id: 1,
    name: "Eten Hunt",
    role: "Agents",
    message: "Thank you very much. I’m glad ...",
    isMe: false,
    profilePic: pinkShirttBoy,
    isOnline: false,
  },
  {
    id: 2,
    name: "Jakob Saris",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    profilePic: brokenMan,
    isOnline: true,
  },
  {
    id: 3,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: yellowBoy,
    isOnline: true,
  },
  {
    id: 4,
    name: "Nadia Lauren",
    role: "agents",
    message: "Thank you very much. I’m glad ...",
    isMe: false,
    lastSeen: 5,
    isUnread: true,
    profilePic: pinkShirttBoy,
    isOnline: false,
  },
  {
    id: 5,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: yellowBoy,
    isOnline: true,
  },
  {
    id: 6,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: brokenMan,
    isOnline: false,
  },
  {
    id: 7,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: pinkShirttBoy,
    isOnline: false,
  },
  {
    id: 8,
    name: "Jakob Saris",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    profilePic: yellowBoy,
    isOnline: false,
  },
  {
    id: 9,
    name: "Eten Hunt",
    role: "agents",
    message: "Thank you very much. I’m glad ...",
    isMe: false,
    profilePic: brokenMan,
    isOnline: true,
  },
  {
    id: 10,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: yellowBoy,
    isOnline: true,
  },
  {
    id: 11,
    name: "Jakob Saris",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    profilePic: brokenMan,
    isOnline: true,
  },
  {
    id: 12,
    name: "Jeremy Zucker",
    role: "Property manager",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    profilePic: pinkShirttBoy,
    isOnline: false,
  },
  {
    id: 13,
    name: "Nadia Lauren",
    role: "agents",
    message: "Thank you very much. I’m glad ...",
    isMe: true,
    lastSeen: 5,
    isUnread: true,
    profilePic: brokenMan,
    isOnline: false,
  },
];

// Dummy Messages List
const messages = [
  {
    id: 1,
    sender: "Sender",
    message: "Hello, how are you?",
    time: moment().format("h:mm A"),
    profilePic: profilePic,
    userId: 1,
  },
  {
    id: 2,
    sender: "Receiver",
    message: "I'm good, thanks!",
    time: moment().add(1, "minute").format("h:mm A"),
    profilePic: profilePic,
    userId: 2,
  },
  {
    id: 3,
    sender: "Sender",
    message: "Here's an image!",
    time: moment().add(2, "minutes").format("h:mm A"),
    profilePic: profilePic,
    imgurl: profilePic,
    userId: 3,
  },
  {
    id: 4,
    sender: "Sender",
    message: "Hello, how are you?",
    time: moment().format("h:mm A"),
    profilePic: profilePic,
    userId: 4,
  },
  {
    id: 5,
    sender: "Receiver",
    message: "I'm good, thanks!",
    time: moment().add(1, "minute").format("h:mm A"),
    profilePic: profilePic,
    userId: 5,
  },
  {
    id: 6,
    sender: "Sender",
    message: "Here's an image!",
    time: moment().add(2, "minutes").format("h:mm A"),
    profilePic: profilePic,
    imgurl: profilePic,
    userId: 6,
  },
  {
    id: 7,
    sender: "Sender",
    message: "I'm good, thanks! Lorem ipsum dolor sit amet.",
    time: moment().add(1, "minute").format("h:mm A"),
    profilePic: profilePic,
    userId: 7,
  },
  {
    id: 8,
    sender: "Receiver",
    message: "Thank you very much. I’m glad!",
    time: moment().format("h:mm A"),
    profilePic: profilePic,
    userId: 8,
  },
  {
    id: 9,
    sender: "Sender",
    message: "Just wanted to check in!",
    time: moment().add(1, "minute").format("h:mm A"),
    profilePic: profilePic,
    userId: 9,
  },
  {
    id: 10,
    sender: "Receiver",
    message: "I'll be there in 10 minutes.",
    time: moment().add(2, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 10,
  },
  {
    id: 11,
    sender: "Sender",
    message: "Got it, thanks!",
    time: moment().add(3, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 11,
  },
  {
    id: 12,
    sender: "Receiver",
    message: "What's the update?",
    time: moment().add(4, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 12,
  },
  {
    id: 13,
    sender: "Sender",
    message: "Nothing much, how about you?",
    time: moment().add(5, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 13,
  },
  {
    id: 14,
    sender: "Receiver",
    message: "I'm still working on it.",
    time: moment().add(6, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 1,
  },
  {
    id: 15,
    sender: "Sender",
    message: "Alright, let me know if you need help.",
    time: moment().add(7, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 2,
  },
  {
    id: 16,
    sender: "Receiver",
    message: "Can you share the file?",
    time: moment().add(8, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 3,
  },
  {
    id: 17,
    sender: "Sender",
    message: "Sure, sending it now!",
    time: moment().add(9, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 4,
  },
  {
    id: 18,
    sender: "Receiver",
    message: "Got it, thanks!",
    time: moment().add(10, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 5,
  },
  {
    id: 19,
    sender: "Sender",
    message: "What time works for you?",
    time: moment().add(11, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 6,
  },
  {
    id: 20,
    sender: "Receiver",
    message: "How about 3 PM?",
    time: moment().add(12, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 7,
  },
  {
    id: 21,
    sender: "Sender",
    message: "3 PM works for me.",
    time: moment().add(13, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 8,
  },
  {
    id: 22,
    sender: "Receiver",
    message: "Great, see you then!",
    time: moment().add(14, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 9,
  },
  {
    id: 23,
    sender: "Sender",
    message: "Have you seen the new update?",
    time: moment().add(15, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 10,
  },
  {
    id: 24,
    sender: "Receiver",
    message: "Yes, it looks good!",
    time: moment().add(16, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 11,
  },
  {
    id: 25,
    sender: "Sender",
    message: "I agree, the UI is much cleaner.",
    time: moment().add(17, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 12,
  },
  {
    id: 26,
    sender: "Receiver",
    message: "The colors are more vibrant too!",
    time: moment().add(18, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 13,
  },
  {
    id: 27,
    sender: "Sender",
    message: "What are you up to this weekend?",
    time: moment().add(19, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 1,
  },
  {
    id: 28,
    sender: "Receiver",
    message: "Just relaxing, probably watch a movie.",
    time: moment().add(20, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 2,
  },
  {
    id: 29,
    sender: "Sender",
    message: "That sounds nice, I might do the same.",
    time: moment().add(21, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 3,
  },
  {
    id: 30,
    sender: "Receiver",
    message: "What movie are you thinking of watching?",
    time: moment().add(22, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 4,
  },
  {
    id: 31,
    sender: "Sender",
    message: "I'm thinking of watching a thriller.",
    time: moment().add(23, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 5,
  },
  {
    id: 32,
    sender: "Receiver",
    message: "Nice! I love thrillers.",
    time: moment().add(24, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 6,
  },
  {
    id: 33,
    sender: "Sender",
    message: "Me too! Do you have any recommendations?",
    time: moment().add(25, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 7,
  },
  {
    id: 34,
    sender: "Receiver",
    message: "I highly recommend 'Inception.'",
    time: moment().add(26, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 8,
  },
  {
    id: 35,
    sender: "Sender",
    message: "Great, I'll check it out.",
    time: moment().add(27, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 9,
  },
  {
    id: 36,
    sender: "Receiver",
    message: "Let me know what you think!",
    time: moment().add(28, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 10,
  },
  {
    id: 37,
    sender: "Sender",
    message: "For sure!",
    time: moment().add(29, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 11,
  },
  {
    id: 38,
    sender: "Receiver",
    message: "Did you get the report I sent?",
    time: moment().add(30, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 12,
  },
  {
    id: 39,
    sender: "Sender",
    message: "Yes, I'm reviewing it now.",
    time: moment().add(31, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 13,
  },
  {
    id: 40,
    sender: "Receiver",
    message: "Any feedback so far?",
    time: moment().add(32, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 1,
  },
  {
    id: 41,
    sender: "Sender",
    message: "It's looking good, but I have a few suggestions.",
    time: moment().add(33, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 2,
  },
  {
    id: 42,
    sender: "Receiver",
    message: "Great, let's go over them.",
    time: moment().add(34, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 3,
  },
  {
    id: 43,
    sender: "Sender",
    message: "Sure! I'll send you a list shortly.",
    time: moment().add(35, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 4,
  },
  {
    id: 44,
    sender: "Receiver",
    message: "Looking forward to it.",
    time: moment().add(36, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 5,
  },
  {
    id: 45,
    sender: "Sender",
    message: "I just updated the file with the suggestions.",
    time: moment().add(37, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 6,
  },
  {
    id: 46,
    sender: "Receiver",
    message: "Thanks for the update.",
    time: moment().add(38, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 7,
  },
  {
    id: 47,
    sender: "Sender",
    message: "You're welcome!",
    time: moment().add(39, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 8,
  },
  {
    id: 48,
    sender: "Receiver",
    message: "Did you check the feedback?",
    time: moment().add(40, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 9,
  },
  {
    id: 49,
    sender: "Sender",
    message: "Yes, I'm working on it.",
    time: moment().add(41, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 10,
  },
  {
    id: 50,
    sender: "Receiver",
    message: "Alright, keep me updated.",
    time: moment().add(42, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 11,
  },
  {
    id: 51,
    sender: "Sender",
    message: "Sure thing.",
    time: moment().add(43, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 12,
  },
  {
    id: 52,
    sender: "Receiver",
    message: "Can you send me the final draft?",
    time: moment().add(44, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 13,
  },
  {
    id: 53,
    sender: "Sender",
    message: "Sending it now.",
    time: moment().add(45, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 1,
  },
  {
    id: 54,
    sender: "Receiver",
    message: "Got it, thanks!",
    time: moment().add(46, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 2,
  },
  {
    id: 55,
    sender: "Sender",
    message: "No problem!",
    time: moment().add(47, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 3,
  },
  {
    id: 56,
    sender: "Receiver",
    message: "When will you be available?",
    time: moment().add(48, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 4,
  },
  {
    id: 57,
    sender: "Sender",
    message: "I'll be free in an hour.",
    time: moment().add(49, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 5,
  },
  {
    id: 58,
    sender: "Receiver",
    message: "Alright, I'll call you then.",
    time: moment().add(50, "minutes").format("h:mm A"),
    profilePic: profilePic,
    userId: 6,
  },
];

const initialState = {
  users,
  messages,
};

const msgSlice = createSlice({
  name: "msgSlice",
  initialState,
  reducers: {
    addMessage: (state, action) => {
      state.messages.push(action.payload);
    },
  },
});

export const { addMessage } = msgSlice.actions;
export default msgSlice.reducer;
